### ISSUE TITLE
Line ending issues on Windows

### ISSUE THREAD

**Issue by sudo-suhas** [bfred-it/shorten-repo-url#10]
I cloned the repo, installed deps but the git attributes file is not configured correctly which results in the following linter errors: 

```
λ yarn test
yarn run v1.3.2
$ xo && ava

  browser-url.js:1:17
  ×    1:17   Expected linebreaks to be LF but found CRLF.  linebreak-style
  ×    2:26   Expected linebreaks to be LF but found CRLF.  linebreak-style

  index.js:1:30
  ‼   26:1    Function shortenURL has a complexity of 23.   complexity
  ×    1:30   Expected linebreaks to be LF but found CRLF.  linebreak-style
  ×    2:76   Expected linebreaks to be LF but found CRLF.  linebreak-style
  ...
  ×  158:29   Expected linebreaks to be LF but found CRLF.  linebreak-style
  ×  159:42   Expected linebreaks to be LF but found CRLF.  linebreak-style

  test.js:1:24
  ×    1:24   Expected linebreaks to be LF but found CRLF.  linebreak-style
  ×    2:28   Expected linebreaks to be LF but found CRLF.  linebreak-style
  ×    3:1    Expected linebreaks to be LF but found CRLF.  linebreak-style
  ...
  
  1 warning
  518 errors
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

This can be fixed by changing the .gitattributes file:
```diff
 * text=auto
+
+*.js text eol=lf
```

However, it is considered a good practice to enable auto-CRLF enabled. To keep it enabled for js files, we could disable the eslint rule `linebreak-style`. But I am not entirely sure how this can be done with `xo`.

**Comment by bfred-it** [comment]
Are you on windows? That's weird because https://github.com/sindresorhus/eslint-config-xo/pull/42 should have fixed it.

**Comment by sudo-suhas** [comment]
Yes, I am on Windows.

The latest version of `xo` which has been released is `0.18.2`(which is what I have). And this version [depends on `eslint-config-xo@^0.18.0`](https://github.com/sindresorhus/xo/blob/v0.18.2/package.json) which won't match the latest version of `eslint-config-xo` - `0.19.0`.

**Comment by bfred-it** [comment]
@sindresorhus any idea of why that’s still happening?

**Comment by sudo-suhas** [comment]
It's just how SemVer works in major version zero(`0.y.z`):
```
λ node
> let semver = require('semver')

> semver.satisfies('0.18.2', '^0.18.0')
true

> semver.satisfies('0.19.0', '^0.18.0')
false
```

With major version as zero, a change such as `{0.18.2 🡲 0.19.0}` is considered a breaking change.

A minor release of `xo` should fix this since the master branch has the changes required for pulling in the latest version of `eslint-config-xo`.

**Comment by bfred-it** [comment]
But I depend on `xo: *` and `xo` specifically has `eslint-config-xo: 0.19.0`

**Comment by sudo-suhas** [comment]
`xo: *` translates to the latest released version which is `0.18.2` and as I mentioned earlier, this specific version depends on `eslint-config-xo@^0.18.0`. So even though a newer version of `eslint-config-xo` is released, we won't get it because the version range does not match(`semver.satisfies('0.19.0', '^0.18.0') // 🡲 false`).

**Comment by sindresorhus** [comment]
> However, it is considered a good practice to enable auto-CRLF enabled.

No, it's not. The best practice is consistency. Just use LF everywhere. There's no longer any good reason to use CRLF.

**Comment by bfred-it** [comment]
Ah got it, so xo just needs a new version. Closing because that’ll come soon at some point.

**Comment by sudo-suhas** [comment]
I am not claiming to know what's better nor am I advocating for `core.autocrlf`(which I have disabled on my own system). But in my experience, the eslint lint endings rule can cause issues on Windows if the `.gitattributes` file is not configured properly(I have seen that in 3 different repos). By default, the rule `core.autocrlf` is enabled on Windows so the path with lowest probability of issues might be to leave the `line-endings` rule disabled.

**Comment by bfred-it** [comment]
Yep, which is what will happen in `xo:0.19` already, on Windows.
