### ISSUE TITLE
Inaccurate compare links

### ISSUE THREAD

**Issue by jerone** [bfred-it/shorten-repo-url#16]
## Input
`https://github.com/BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec` [🔗](https://github.com/BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec)
`https://github.com/BrowserSync/browser-sync/compare/client-ts` [🔗](https://github.com/BrowserSync/browser-sync/compare/client-ts)
`https://github.com/BrowserSync/browser-sync/compare/client-ts...master`  [🔗](https://github.com/BrowserSync/browser-sync/compare/client-ts...master)

## Output
BrowserSync/browser-sync/compare/62007c8b944808d1b46d42d5e22fa65883d1eaec
BrowserSync/browser-sync/compare/client-ts
BrowserSync/browser-sync@`client-ts...master`

## Expected
BrowserSync/browser-sync@`62007c8` (compare)
BrowserSync/browser-sync@`client-ts` (compare)
BrowserSync/browser-sync@`client-ts...master` (compare)

**Comment by jerone** [comment]
I'll take a stab at it...

**Comment by jerone** [comment]
:shipit:

**Comment by bfred-it** [comment]
Thanks for the reminder! Forgot. Coming as 1.5.2
