### ISSUE TITLE
Confusing usage with refined-github

### ISSUE THREAD

**Issue by sudo-suhas** [bfred-it/shorten-repo-url#8]
Hey.. So this is what the usage looks like with `refined-github`:

![image](https://user-images.githubusercontent.com/22251956/32281857-0886abe0-bf46-11e7-9b1e-63a6b29295e1.png)

Which shows incorrect usage examples. Do you think anything can be done about this?

**Comment by bfred-it** [comment]
You made me worry for a moment, then I remembered that we reverted a change in refined-github because of this issue. Update the extension to get this fix: https://github.com/sindresorhus/refined-github/issues/789

**Comment by sudo-suhas** [comment]
My apologies and thanks!

**Comment by bfred-it** [comment]
No worries! Thanks for reporting it!
